// examples/vue-example/src/App.vue
<script setup lang="ts">
import Vaults from './components/Vaults.vue';
import wallet from './wallet';
</script>

<template>
  <Vaults />

  <button @click="wallet.methods.addMnemonicVault()">addMnemonicVaultCreate</button>
  <button @click="wallet.methods.addMnemonicVault({ mnemonic: 'tag refuse output old identify oval major middle duck staff tube develop', source: 'import' })">
    addMnemonicVaultImported
  </button>
</template>

// examples/react-example/src/App.tsx
import { useVaults } from '@cfx-kit/wallet-core-react-inject/src';
import wallet from './wallet';

const Vaults = () => {
  const vaults = useVaults();
  return <h2>valuts length: {Array.isArray(vaults) ? vaults?.length : -1}</h2>;
};

function IndexPopup() {

  return (
    <div>
      <Vaults />
      <button
        onClick={async () => {
          wallet.methods.addMnemonicVault();
        }}
      >
        addMnemonicVaultCreate
      </button>
      <button
        onClick={async () => {
          wallet.methods.addMnemonicVault({ mnemonic: 'tag refuse output old identify oval major middle duck staff tube develop', source: 'import' });
        }}
      >
        addMnemonicVaultImported
      </button>
    </div>
  );
}

export default IndexPopup;
